/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergesort;

import org.junit.Test;
import static org.junit.Assert.*;

public class MergeSortTest {
    private int[] arr;

    @Test (expected = NullPointerException.class)
    public void nullArray() {
        MergeSort.mergeSort(arr);
    }

    @Test
    public void oneElement() {
        arr = new int[]{99};
        assertArrayEquals(
                "One element array should return itself",
                new int[]{99},
                MergeSort.mergeSort(arr));
    }

    @Test
    public void twoElement() {
        arr = new int[]{99, 8};
        assertArrayEquals(
                "Two element array should be sorted",
                new int[]{8, 99},
                MergeSort.mergeSort(arr));
    }

    @Test
    public void tenElement() {
        arr = new int[]{7, 6, 3, 4, 1, 2, 8, 9, 0, 5};
        assertArrayEquals(
                "Ten element array should be sorted",
                new int[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
                MergeSort.mergeSort(arr));
    }

    @Test
    public void duplicateElement() {
        arr = new int[]{3, 7, 3, 6, 3, 7};
        assertArrayEquals(
                "Duplicate element array should be sorted",
                new int[]{3, 3, 3, 6, 7, 7},
                MergeSort.mergeSort(arr));
    }
}
