/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionsort;

import org.junit.Test;

import java.util.Arrays;

import static insertionsort.InsertionSort.insertionSort;
import static org.junit.Assert.*;

public class InsertionSortTest {
    private int[] arr;
    private int[] emptyArr = new int[]{};

    @Test (expected = NullPointerException.class)
    public void testEmptyInput() {
        insertionSort(emptyArr);
    }

    @Test public void testOneElemArray() {
        arr = new int[]{4};
        System.out.println(Arrays.toString(insertionSort(arr)));
        assertArrayEquals("Array should be in order", new int[]{4}, insertionSort(arr));
    }

    @Test public void testTwoElemArray() {
        arr = new int[]{7, 4};
        System.out.println(Arrays.toString(insertionSort(arr)));
        assertArrayEquals("Array should be in order", new int[]{4, 7}, insertionSort(arr));
    }

    @Test public void testFourElemArray() {
        arr = new int[]{11, 7, 4, -9};
        System.out.println(Arrays.toString(insertionSort(arr)));
        assertArrayEquals("Array should be in order", new int[]{-9, 4, 7, 11}, insertionSort(arr));
    }
}
