/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quicksort;

import org.junit.Test;
import static org.junit.Assert.*;

public class QuickSortTest {
    @Test public void testSomeLibraryMethod() {
        QuickSort classUnderTest = new QuickSort();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
