/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionsort;

import java.util.Arrays;

public class InsertionSort {
    public static void main(String[] args) {
        int[] arr = new int[]{};
        System.out.println(Arrays.toString(insertionSort(arr)));

    }

    public static int[] insertionSort(int[] array) {
        if(array == null || array.length == 0) {
            throw new NullPointerException("Your input array is empty");
        }

        if(array.length == 1) {
            return array;
        }

        for(int i = 1; i < array.length; i ++) {
            int j = i - 1;
            int temp = array[i];

            while(j >= 0 && temp < array[j]) {
                array[j + 1] = array[j];
                j = j - 1;
            }

            array[j + 1] = temp;
        }
        return array;
    }
}
