/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.Test;
import static org.junit.Assert.*;
import graph.Graph.*;

import java.util.HashSet;

public class GraphTest {
    private Graph<Integer> testGraph;

    @Test
    public void init() {
        testGraph = new Graph<>();

    }

    @Test
    public void emptyGraph() {
        assertNull("Declared but not instantiated graph should be null", testGraph);

        init();

        assertEquals("instantiated graph should have size of 0", 0, testGraph.size());
    }

    @Test
    public void addNodeNoNeighbors() {
        init();

        Node three = testGraph.addNode(3);
        testGraph.addNode(3);
        testGraph.getNodes().forEach( vertex -> {
            System.out.println(vertex.data);
            System.out.println(testGraph.getNeighbors(vertex));
        });

        assertEquals("size should be 2", 2, testGraph.size());

        assertEquals("Get neighbors should return []", new HashSet(), testGraph.getNeighbors(three));
    }

    @Test
    public void addNeighborsAndEdge() {
        init();

        Node node1 = testGraph.addNode(3);
        Node node2 = testGraph.addNode(3);

        testGraph.addEdge(node1, node2, 90);
        System.out.println(node1.edges);

        assertTrue(
                "Node1 should have node2 as the only neighbor",
                testGraph.getNeighbors(node1).contains(node2)
                );

        assertEquals(
                "Node1 neighbors list should have size of 1",
                1,
                testGraph.getNeighbors(node1).size()
        );

        assertTrue(
                "Node2 should have node1 as a neighbor",
                testGraph.getNeighbors(node2).contains(node1)
        );

        assertEquals(
                "Node2 neighbors list should have size of 1",
                1,
                testGraph.getNeighbors(node2).size()
        );

        assertEquals(
                "Node 1 edge should contain one edge with weight of 90",
                "[Edge: weight = 90]",
                node1.edges.toString()
        );

        assertEquals(
                "Node 2 edge should contain one edge with weight of 90",
                "[Edge: weight = 90]",
                node2.edges.toString()
        );
    }
}
