/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array_shift;

public class Library {

    /**
     * Takes in an array and the value to be added.
     * Without utilizing any of the built-in methods available,
     * returns an array with the new value added at the middle index.
     * If the original array has odd number of elements,
     * new value will be added to second half of result array.
     *
     * @param inputArr int[]
     * @param valueToBeAdded int
     * @return newArr int[]
     */
    public int[] insertShiftArray(int[] inputArr, int valueToBeAdded) {

        if(inputArr.length == 0) {
            return inputArr;
        }

        int[] returnArr = new int[inputArr.length + 1];
        int indexToBeAdded;

        if(inputArr.length == 1) {
            returnArr[0] = inputArr[0];
            returnArr[1] = valueToBeAdded;
            return returnArr;
        }

        //if original length is odd, have new value added to second half of result array
        if(inputArr.length % 2 == 1) {
            indexToBeAdded = (inputArr.length + 1) / 2;
        } else {
            indexToBeAdded = inputArr.length / 2;
        }
        int returnArrIndexCount = 0;

        for(int i = 0; i < inputArr.length; i++) {
            if(i == indexToBeAdded) {
                returnArr[i] = valueToBeAdded;
                returnArr[i + 1] = inputArr[i];
                returnArrIndexCount+=2;
                continue;
            }
            returnArr[returnArrIndexCount] = inputArr[i];
            returnArrIndexCount++;
        }

        return returnArr;
    }
}
