/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animal_shelter;

import java.util.LinkedList;
import java.util.List;

public class AnimalShelter {
    List<Animal> list;

    /**
     * Constructor for animal shelter object
     */
    public AnimalShelter() {
        list = new LinkedList<>();
    }

    /**
     * Adds a new animal to animal shelter
     * @param animal Animal object, either Cat or Dog
     */
    public void enqueue(Animal animal) {
        list.add(animal);
    }

    /**
     * Removes the first occurrence of an animal
     * based on pref
     * @param pref String Cat or Dog
     * @return removed Animal or null if not found
     */
    public Animal dequeue(String pref) {
        if(list.size() == 0) {
            throw new NullPointerException("List is empty");
        }

        if(verifyPref(pref)) {
            Animal result;
            String comparison = "class animal_shelter." + pref;
            for(Animal animal : list) {
                System.out.println(animal.getClass().toString());
                //if animal class equals pref, remove and return
                if(animal.getClass().toString().equals(comparison)) {
                    result = animal;
                    list.remove(animal);
                    return result;
                }
            }
        }
        //if pref is not cat or dog, or if animal not found
        return null;
    }

    //helper - checks if pref is Cat or Dog
    private boolean verifyPref(String pref) {
        if(!pref.equals("Cat") && !pref.equals("Dog")) {
            return false;
        }
        return true;
    }
}
