/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

import org.junit.Test;
import static org.junit.Assert.*;

public class NodeTest {
    @Test public void testSomeLibraryMethod() {
//        Node classUnderTest = new Node();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethodethod());
    }
}
