/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package arr_binary_search;

public class Library {
    /**
     * Binary search looks looks through input array
     * for search element. Boundaries change based on
     * whether the middle element is less or more than
     * search element.
     * @param array sorted int array
     * @param search int
     * @return int, index of element if found else -1
     */
    public int binarySearch(int[] array, int search) {
        if(array.length == 0) {
            return -1;
        }
        int left = 0;
        int right = array.length - 1;
        while (left <= right) {
            int mid = (left + right) / 2;
            if(array[mid] == search) {
                return mid;
            } else if (array[mid] > search) {
                right = mid - 1;
            } else {
                left = mid + 1;
            }
        }
        return -1;
    }
}
