/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

public class Node<E extends Comparable<? super E>> {
    E data;
    Node<E> left;
    Node<E> right;

    public Node(E data, Node<E> left, Node<E> right) {
        this.data = data;
        this.left = left;
        this.right = right;
    }

    public E getData() {
        return data;
    }

    public void setData(E data) {
        this.data = data;
    }

    public Node<E> getLeft() {
        return left;
    }

    public Node<E> getRight() {
        return right;
    }
}
