/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package array_shift;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void oddNumArr() {
        int[] oddNumArr = new int[] {2, 3, 4};
        int[] resultOddNumArr = new int[] {2, 3, 15, 4};
        Library classUnderTest = new Library();
        assertArrayEquals("someLibraryMethod should return {2, 3, 15, 4}", resultOddNumArr,
                classUnderTest.insertShiftArray(oddNumArr, 15));
    }

    @Test public void evenNumArr() {
        int[] evenNumArr = new int[] {2, 3, 4, 5};
        int[] resultNumArr = new int[] {2, 3, 15, 4, 5};
        Library classUnderTest = new Library();
        assertArrayEquals("someLibraryMethod should return {2, 3, 15, 4, 5}", resultNumArr,
                classUnderTest.insertShiftArray(evenNumArr, 15));
    }

    @Test public void oneElArr() {
        int[] oneElArr = new int[] {2};
        int[] resultNumArr = new int[] {2, 15};
        Library classUnderTest = new Library();
        assertArrayEquals("someLibraryMethod should return {2, 15}", resultNumArr,
                classUnderTest.insertShiftArray(oneElArr, 15));
    }
    @Test public void zeroElArr() {
        int[] zeroElArr = new int[] {};
        Library classUnderTest = new Library();
        assertArrayEquals("someLibraryMethod should return empty array", zeroElArr,
                classUnderTest.insertShiftArray(zeroElArr, 15));
    }
}
