/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksandqueues;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class StackTest {
    Stack testStack;

    @Before
    public void init() {
        testStack = new Stack();
    }

    @Test (expected = NullPointerException.class)
    public void emptyStackTest() {
        testStack.peek();
    }

    @Test
    public void addToList() {
        testStack.push(1);
        assertEquals("Size should return 1 after one element is added", 1, testStack.getSize());
    }

    @Test
    public void deleteFromListOfOne() {
        addToList();
        assertEquals("Pop should return 1", 1, testStack.pop());
    }

    @Test
    public void addMany(){
        addToList();
        testStack.push(2);
        testStack.push(3); // 3, 2, 1
        assertEquals("Top data should return 3", 3, testStack.getTopData());
        assertEquals("Size should return 3", 3, testStack.getSize());
        assertEquals("Pop should return 3", 3, testStack.pop());
        assertEquals("Peek should return 2", 2, testStack.peek());
        assertEquals("Pop should return 2", 2, testStack.pop());
        assertEquals("Pop should return 1", 1, testStack.pop());
    }
}
