/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.Test;
import static org.junit.Assert.*;

public class HashTableTest {
    @Test public void testSomeLibraryMethod() {
        HashTable classUnderTest = new HashTable();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
