/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacksandqueues;

public class Node {
    private Node next;
    private int data;

    public Node(int data, Node next) {
        this.data = data;
        this.next = next;
    }

    public int getData() {
        return this.data;
    }

    public Node getNext() {
        return this.next;
    }

    public void setNext(Node next) {
        this.next = next;
    }

    public void setData(int data) {
        this.data = data;
    }
}
